// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Enums;
// using Newtonsoft.Json;
// using Newtonsoft.Json.Converters;
using UnityEngine;

namespace DataTables
{
    [System.Serializable]
    public class GameConst : ScriptableObject
{
        [Serializable]
        public class DataClass
        {
            public int ComboMin;
            public string CustomizationDataSaveKey;
            public string TopBrickNumberSaveKey;
            public int AdsRewardBeansCount;
        }

    public DataClass Data;
}
}

